language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - "node"
branches:
    only:
        - master
notifications:
  email: false
before_script:
  - npm prune
  - npm install
script:
  - npm run cover
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
