#!/usr/bin/env node

if (process.argv.slice(2).length === 0) {
    console.log("Error:", "For more informations, see the manual: fn-cli help\n");
    return;
}

const Cli = require('./index.js');
const command = new Cli();
command.cliCommands();
